root: true
env:
  node: true
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      config: tsconfig.json
      alwaysTryTypes: true
overrides:
  - files: ["*.ts", "*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      ecmaFeatures:
        jsx: true
      ecmaVersion: 2020
      sourceType: module
plugins:
  - react
rules:
  {
    "@typescript-eslint/no-misused-promises": 0,
    "@typescript-eslint/prefer-optional-chain": 0,
    "@typescript-eslint/strict-boolean-expressions": 0,
  }
