version: '3.5'

networks:
  iroha-network:
    name: iroha-network
    attachable: true

services:
  iroha-server:
    build: 
      context: ../
      dockerfile: Dockerfile.server
    container_name: iroha-server
    environment: 
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_ID=${ADMIN_ID}
      - DOMAIN=${DOMAIN}
      - ADMIN_PRIVATE_KEY=${ADMIN_PRIVATE_KEY}
      - TOKEN_KEY=${TOKEN_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - IROHA_PORT=${IROHA_PORT}
    depends_on:
      - iroha-postgres
    ports:
      - 4000:4000
    
  iroha-client:
    build: 
      context: ../
      dockerfile: Dockerfile.client
    container_name: iroha-client
    environment:
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - iroha-server
    ports:
      - 3000:3000

  iroha:
    image: hyperledger/iroha:latest
    container_name: iroha
    depends_on:
      - iroha-postgres
    tty: true
    environment:
      - KEY=keys/node0
    entrypoint:
      - /opt/iroha_data/entrypoint.sh
    networks:
      - iroha-network
    volumes:
      - ./iroha:/opt/iroha_data
    ports:
      - 50051:50051

  iroha-postgres:
    image: postgres:latest
    container_name: iroha-postgres
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    networks:
      - iroha-network