root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      config: tsconfig.json
      alwaysTryTypes: true
overrides:
  - files: ["*.ts"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      ecmaVersion: 2020
      sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  {
    "@typescript-eslint/no-misused-promises": 0,
    "@typescript-eslint/prefer-optional-chain": 0,
    "@typescript-eslint/strict-boolean-expressions": 0,
  }
